# BundleEnabled won't need restart anymore! Hell yeah!!!
BundleEnabled: true
NoPermission: '&cNot enough permissions!'
ConfigReloaded: '&aConfig has been successfully reloaded!'
UnknownCommands: '&cUnknown command!'