  name: CraftableBundle
  main: com.katanamajesty.CraftableBundle
  version: ${version}
  description: Добавляет крафт мешков из 1.18
  api-version: 1.17
  commands:
    craftablebundle:
      description: позволяет перезагружать плагин
      aliases:
        - cbundle